<form action="<?php $this->Route('home.update');?>" method="post">
    <fieldset>
        <legend>Actualizar Usuario <?php echo $this->user->name?></legend>
        <label>Usuario:</label>
        
        <input type="text" hidden value="<?php echo $this->user->id?>" name="id">
        <input type="text" value="<?php echo $this->user->name;?>" name="name">
        <label>Nombre de Usuario:</label>
        <input type="text" value="<?php echo $this->user->username;?>" name="username">
        <input type="submit" value="Actualizar">
    </fieldset>
</form>